name: Run holamundodiego.js

on: 
  push:
    branches:
      - main

jobs:
  run-holamundo:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4  # Se ha actualizado a la versión más reciente

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Se ha actualizado a la versión más reciente
      with:
        node-version: '20'  # Usar la versión más reciente de Node.js

    - name: Run holamundodiego.js
      run: node holamundodiego.js
